name: captivate
favicon: null
layout_spectrum: 0
typography_spectrum: 0.95117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8670a'
    - '#12469d'
    - '#fffefe'
    - '#6886b7'
    - '#360000'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
