name: captivate
favicon: null
layout_spectrum: 0.50763
typography_spectrum: 0.95117
title: CAPTIVATE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d98200'
    - '#19203a'
    - '#aba597'
    - '#fcffff'
    - '#a34500'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
