name: captivate
favicon: null
layout_spectrum: 0.25941
typography_spectrum: 0.4431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1dcd8'
    - '#e08e42'
    - '#45484d'
    - '#619faa'
    - '#131313'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.8728603166528046
  rhythmicContrast: 0.7201216295361519
purpose: []
